### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by compilercomplied** [rebkwok/kpcli#11]
Sorry to be THAT guy that uses windows 😄

When trying to run `kpcli` in a windows box I'm greeted by an AttributeError

```
  File "C:\Users\___\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kpcli\cli.py", line 26, in <module>
    signal.signal(signal.SIGALRM, inputTimeOutHandler)
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

This seems to be related to alarm(2) not being available on windows [1].

Looking at [the code](https://github.com/rebkwok/kpcli/blob/1c64e7274345d28ebc2607e22211a4ee9f6dbe7f/kpcli/utils.py#L103), it seems it is being used to raise an error when the input is hanging for too long (as a security measure I guess?).

Is there any way we can work around this limitation for windows users?

[1] https://docs.python.org/3/library/signal.html#signal.SIGALRM

**Comment by rebkwok** [comment]
Hi there, I wrote this package as a tiny utility for my own use. While it's great that others are finding it useful, I'm afraid I don't have time - and being a mac/linux user, I don't really have the time or motivation - to add windows support. PRs welcome though :)

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
