### ISSUE TITLE
Add the ability to change entry name/ 

### ISSUE THREAD

**Issue by ReneFroger** [rebkwok/kpcli#16]
Hi there! Thanks for creating this package, it's really appreciated!

However, I wanted to change the entry name and to my surprise this was not possible. 

With `kpcli edit [name of entry]` you could only edit entry's attributes like username, notes, or url, but not the name of entry by itself. Could that be possible too?

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
