### ISSUE TITLE
Add support for profile env var

### ISSUE THREAD

**Issue by guyguy333** [rebkwok/kpcli#18]
Hello,

Similarly to AWS_PROFILE for AWS_CLI, it would be useful to set profile using env var like `KEEPASSDB_PROFILE` instead of adding "-p" to all commands

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
