### ISSUE TITLE
Add support for extra fields

### ISSUE THREAD

**Issue by guyguy333** [rebkwok/kpcli#19]
Hi,

It would be useful to be able to get an extra field (not password) of an entry

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
