### ISSUE TITLE
wl-copy/wl-paste support

### ISSUE THREAD

**Issue by WeaponX1** [rebkwok/kpcli#2]
Hello, are there any plans to also support wayland clipboard as an alternative to xclip? 

There is currently a wl-clipboard-x11 wrapper script for xclip but it doesn't work. Appreciate if this can be addressed for wayland users.

**Comment by pmorch** [comment]
Since you didn't get a response, I'll add:

It seems to me that this project uses Pyperclip, so you might address that there. I'm not a huge wayland expert but I found:

[Running on Wayland causes no clipboard mechanism to be found if `$DISPLAY` is undefined · Issue #220 · asweigart/pyperclip](https://github.com/asweigart/pyperclip/issues/220)

Hope that helps a little.

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
