### ISSUE TITLE
Custom output

### ISSUE THREAD

**Issue by guyguy333** [rebkwok/kpcli#20]
Hi,

Currently, output format is static. It would be useful to output as JSON or YAML so we can easily pipe using jq or yq. Also, it could be useful to get "raw" password so we can directly use value in next piped command.

**Comment by Nexxxy** [comment]
+1

currently i have modified the cli.py
`
@app.command("get-pw")
def get_entry(
    ctx: typer.Context,
    name: str = typer.Argument(
        ...,
        help="Name (or partial name) of item to fetch only the pw without info - for shell var purposes.  Specify group with / e.g. root/my_item",
    ),    
):
    """
    Fetch details for a single entry
    """
    entries = ctx_connector(ctx).find_entries(name)
    if not entries:
        typer.echo("No matching entry found")
        raise typer.Exit()
    for entry in entries:        
        details = ctx_connector(ctx).get_details(entry, True)
        for field, value in details.items():
            if (field == "password"):
                typer.echo(f"xpwd: {value}")
`

with that i can grep for xpwd and reduce it inside a shell script like 
`
#/bin/bash
exec_kp=$(kpcli get-pw "token" | grep "xpwd:")
pwdx=${exec_kp:24}
`
pwdx can be used within this script as the pwd.
Note that you lose all promts :D

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
