### ISSUE TITLE
Documentation: wrong spelling for KEEPASSDB_KEYFILE

### ISSUE THREAD

**Issue by otheus** [rebkwok/kpcli#25]
On Readme.md you've got the wrong spelling for environment variable `KEEPASSDB_KEYFILE`. You have it as `KEYPASSDB_KEYFILE` which does not work.

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
