### ISSUE TITLE
How do you use this from the CLI

### ISSUE THREAD

**Issue by SaulMoonves** [rebkwok/kpcli#27]
I have no clipboard because I am using the console. Is there a way to make this just output the password to stdout?

**Comment by simon-20** [comment]
I also had a problem here, the functionality to paste to the clipboard just doesn't work for me on KDE Plasma running Ubuntu.

It turns out, though, that you can get it to show the password. There is a `--show-password` or `-s` option. It just isn't documented anywhere.

So you can just do:

`kpcli get -s 'Entry Name'`

Or, if running from a local install using poetry:

`python -m poetry run kpcli get -s 'Entry Name'`

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
