### ISSUE TITLE
Following instructions to install from source gives 'Poetry configuration file invalid' error

### ISSUE THREAD

**Issue by simon-20** [rebkwok/kpcli#28]
Running `poetry install`

```
  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
```

If I remove the section with the dependencies for the tests, this error does not appear.

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
