### ISSUE TITLE
Support for field references

### ISSUE THREAD

**Issue by kimdre** [rebkwok/kpcli#9]
I use [field references](https://keepass.info/help/base/fieldrefs.html) in my keepass database entries.
It seems that getting values from entries with a reference is not yet supported, as the `get` command can only return the reference strings (e.g. `{REF:U@I:E7B775612C7644C1BD0BB112A9985D46}`).
Is it planned to support/implement this feature?

**Comment by rebkwok** [comment]
Closing as this project is no longer actively maintained. The project it is based on, KeePassX, has been deprecated since 2021. Please consider switching to [KeePassXC](https://keepassxc.org/) which is based on KeePassX and is compatible with the same .kdbx file format. KeePassXC ships with a command line utility which does more or less everything you'd want this package for (and some more).
